#!/bin/bash
#
# seth-client Startup script for the Seth client
#
# chkconfig: - 98 02
# description: Client component of the Seth systems integration framework.

### BEGIN INIT INFO
# Provides: seth-client
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Should-Start: $named $time
# Should-Stop: $named $time
# Short-Description: Startup script for the Seth client
# Description: Client component of the Seth systems integration framework.
### END INIT INFO

# Source function library
. /etc/init.d/functions

exec="/usr/bin/seth-client"
prog="seth-client"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

config=${CONFIG-/etc/seth/client.rb}
pidfile=${PIDFILE-/var/run/seth/client.pid}
lockfile=${LOCKFILE-/var/lock/subsys/$prog}
logfile=${LOGFILE-/var/log/seth/client.log}
interval=${INTERVAL-1800}
splay=${SPLAY-20}
options=${OPTIONS-}

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon seth-client -d -c "$config" -L "$logfile" -P "$pidfile" -i "$interval" -s "$splay" "$options"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile seth-client
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart () {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p $pidfile seth-client -HUP
    retval=$?
    echo
    return $retval
}

run() {
    echo -n $"Triggering run of $prog: "
    killproc -p $pidfile seth-client -USR1
    retval=$?
    echo
    return $retval
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    run)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|run}"
        exit 2
esac
exit $?
